name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions: {}

env:
  CARGO_TERM_COLOR: always
  # renovate: datasource=github-tags depName=rust lookupName=rust-lang/rust versioning=semver
  RUST_VERSION: 1.90.0
  # renovate: datasource=github-releases depName=cargo-insta lookupName=mitsuhiko/insta versioning=semver
  CARGO_INSTA_VERSION: 1.43.2

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Install cargo-insta
        run: curl -LsSf https://github.com/mitsuhiko/insta/releases/download/${CARGO_INSTA_VERSION}/cargo-insta-installer.sh | sh

      - run: cargo fetch --locked

      - run: cargo fmt --all --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

      - run: cargo doc --no-deps --document-private-items --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"

      - run: cargo test --doc

      - id: run_tests
        run: cargo insta test --require-full-match --unreferenced=reject --all-targets
        env:
          INSTA_UPDATE: new

      - if: ${{ failure() && steps.run_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: failed-snapshots
          path: "**/snapshots/*.snap.new"